'use client';
import {useMemo,useState} from 'react';
import {zones,categories,baseline} from '../lib/data';
import {forecastDemand,forecastMethod} from '../lib/forecast';
import {rankLocations,assortmentPlan,capacityPlan} from '../lib/optimizer';
export default function Home(){
 const [tab,setTab]=useState('Overview'),[demand,setDemand]=useState(1),[budget,setBudget]=useState(50),[storage,setStorage]=useState(80),[delivery,setDelivery]=useState(20),[q,setQ]=useState(''),[answer,setAnswer]=useState(''),[loading,setLoading]=useState(false);
 const forecast=useMemo(()=>forecastDemand({baseline,demandMultiplier:demand}),[demand]);
 const locations=useMemo(()=>rankLocations(zones),[]),best=locations[0];
 const assortment=useMemo(()=>assortmentPlan(categories,{budget,storage,demandMultiplier:demand}),[budget,storage,demand]);
 const cap=useMemo(()=>capacityPlan(forecast,demand),[forecast,demand]);
 const coverage=Math.max(58,Math.min(95,Math.round(72-(demand-1)*18+(assortment.coverage-58)*.18)));
 const utilization=Math.min(99,Math.round(81+(demand-1)*55+(storage-80)*.15));
 const availability=Math.max(82,Math.min(98,Math.round(95-(demand-1)*30+(budget-50)*.08)));
 async function ask(){setLoading(true);setAnswer('');try{const r=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q||'Explain the current recommendation.',forecast,location:best,assortment,capacity:cap,customerImpact:{coverage,availability},assumptions:{demand,budget,storage,delivery}})});const d=await r.json();setAnswer(d.text||d.error||'No explanation returned.')}catch(e){setAnswer('Copilot unavailable. Add GEMINI_API_KEY to Vercel and redeploy.')}finally{setLoading(false)}}
 return <main className="shell"><header className="top"><div className="brand"><h1>UFC Expansion Command Center</h1><p>Demand Forecasting, Selection & Urban Fulfillment Planning Platform</p></div><div className="badge">Independent case study · Synthetic demo data</div></header>
 <section className="kpis"><K l="Forecast demand / day" v={forecast.final.toLocaleString()} d="vs baseline"/><K l="Selection coverage" v={coverage+'%'} d="customer demand covered"/><K l="Capacity utilization" v={utilization+'%'} d="projected peak"/><K l="Availability" v={availability+'%'} d="projected target"/><K l="Recommended UFC" v={best.name} d={'+'+best.incrementalCoverage+'% coverage'}/></section>
 <nav className="tabs">{['Overview','Forecast','Expansion','Assortment','Scenario'].map(x=><button className={'tab '+(tab===x?'active':'')} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==='Overview'&&<div className="grid"><section className="panel"><h2>Network expansion</h2><div className="sub">Existing footprint and candidate UFC opportunities</div><div className="map"><N c="good a" t="Saket" n="M1"/><N c="good b" t="Gurgaon" n="M2"/><N c="good c" t="Noida" n="M3"/><N c="a d" t="Rajouri" n="M4"/><N c="hot e" t="UFC pilot" n="U1"/><N c="hot f" t="Candidate" n="+"/><div className="legend">● Existing facility &nbsp; ● Candidate / UFC</div></div></section><section className="panel"><h2>Recommended expansion</h2><div className="sub">Transparent scoring across coverage, overlap, investment and delivery</div><div className="rec"><h3>Launch {best.name} UFC</h3><p>Highest incremental customer coverage among evaluated candidates while maintaining a reasonable investment and delivery profile.</p><div className="metrics"><M v={'+'+best.incrementalCoverage+'%'} l="coverage gain"/><M v={best.delivery+' min'} l="expected delivery"/><M v={'₹'+best.cost+'L'} l="illustrative investment"/></div><div className="actions"><button className="primary" onClick={()=>setTab('Scenario')}>Simulate scenario</button><button className="secondary" onClick={()=>setTab('Assortment')}>Plan assortment</button></div></div><div className="scenario"><b>Forecast signal:</b> {forecast.final.toLocaleString()} orders/day · {forecast.confidence}% confidence.</div></section></div>}
 {tab==='Forecast'&&<section className="panel"><h2>Demand forecast</h2><div className="sub">{forecastMethod}</div><div className="bars">{forecast.weekly.map(w=><div className="bar" key={w.week}><span>{w.week}</span><div className="track"><div className="fill" style={{width:Math.min(100,w.orders/120)+'%'}}/></div><b>{w.orders.toLocaleString()}</b></div>)}</div><div className="scenario"><b>Forecast range:</b> {forecast.low.toLocaleString()}–{forecast.high.toLocaleString()} · <b>Confidence:</b> {forecast.confidence}%</div></section>}
 {tab==='Expansion'&&<section className="panel"><h2>UFC expansion opportunities</h2><div className="sub">Ranked using explicit product decision factors.</div><table className="table"><thead><tr><th>Location</th><th>Demand</th><th>Coverage gain</th><th>Overlap</th><th>Delivery</th><th>Investment</th><th>Decision</th></tr></thead><tbody>{locations.map((x,i)=><tr key={x.id}><td><b>{x.name}</b></td><td>{(x.demand/1000).toFixed(0)}K</td><td>+{x.incrementalCoverage}%</td><td>{x.overlap}%</td><td>{x.delivery} min</td><td>₹{x.cost}L</td><td><span className={'pill '+(i===0?'green':i===1?'amber':'red')}>{i===0?'Recommended':i===1?'Evaluate':'Deprioritize'}</span></td></tr>)}</tbody></table></section>}
 {tab==='Assortment'&&<section className="panel"><h2>Selection & assortment planning</h2><div className="sub">Prioritize categories using demand, growth, margin, availability and storage.</div><table className="table"><thead><tr><th>Category</th><th>Demand</th><th>Growth</th><th>Margin</th><th>Availability</th><th>Decision</th></tr></thead><tbody>{categories.map(c=>{const add=assortment.selected.some(x=>x.name===c.name);return <tr key={c.name}><td><b>{c.name}</b></td><td>{(c.demand/1000).toFixed(1)}K</td><td>+{c.growth}%</td><td>{c.margin}%</td><td>{c.availability}%</td><td><span className={'pill '+(add?'green':'amber')}>{add?'Add / expand':'Stage'}</span></td></tr>})}</tbody></table><div className="scenario"><b>Recommendation:</b> {assortment.skuSlots.toLocaleString()} illustrative SKU slots · {assortment.coverage}% selection coverage · {assortment.storage}% storage allocation.</div></section>}
 {tab==='Scenario'&&<section className="panel"><h2>Scenario simulator</h2><div className="sub">Change assumptions and see how the product recommendation responds.</div><div className="controls"><C l={'Demand: '+Math.round(demand*100)+'%'} v={demand} min=".75" max="1.4" step=".05" set={setDemand}/><C l={'Inventory budget: ₹'+budget+'L'} v={budget} min="30" max="80" step="5" set={setBudget}/><C l={'Storage capacity: '+storage+'%'} v={storage} min="60" max="95" step="5" set={setStorage}/><C l={'Delivery target: '+delivery+' min'} v={delivery} min="10" max="30" step="5" set={setDelivery}/></div><div className="scenario"><b>Decision:</b> {cap.gap>0?'Add or rebalance approximately '+cap.gap.toLocaleString()+' units of daily capacity.':'Current capacity is sufficient; prioritize the highest-value selection gaps.'} Forecast peak is {cap.peak.toLocaleString()} vs target {cap.target.toLocaleString()}.</div><div className="rec" style={{marginTop:12}}><h3>Customer impact</h3><p>The scenario projects {coverage}% selection coverage and {availability}% availability at the selected constraints.</p><div className="metrics"><M v={cap.gap.toLocaleString()} l="capacity gap"/><M v={coverage+'%'} l="selection coverage"/><M v={availability+'%'} l="availability"/></div></div></section>}
 <section className="copilot"><b>UFC Planning Copilot</b><div className="sub">Gemini explains computed recommendations; it does not generate the underlying numbers.</div><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask: Why is this location recommended? Why should assortment expand now? What is the main trade-off?"/><div className="actions"><button className="primary" onClick={ask} disabled={loading}>{loading?'Thinking...':'Ask Gemini'}</button></div>{answer&&<div className="scenario" style={{whiteSpace:'pre-wrap'}}>{answer}</div>}</section>
 <footer className="footer"><b>Independent product case study.</b> Demo demand, inventory, customer and facility data are synthetic/illustrative. Forecasting uses a transparent baseline + trend + seasonality + event model; the data layer is intentionally separated so real operational data can replace it later. This does not represent Amazon internal systems, data or algorithms.</footer>
 </main>
}
function K({l,v,d}){return <div className="kpi"><div className="label">{l}</div><div className="value">{v}</div><div className="delta">{d}</div></div>}function M({v,l}){return <div className="metric"><b>{v}</b><span>{l}</span></div>}function N({c,t,n}){return <div className={'node '+c}>{n}<span>{t}</span></div>}function C({l,v,min,max,step,set}){return <div className="control"><label>{l}</label><input type="range" min={min} max={max} step={step} value={v} onChange={e=>set(+e.target.value)}/></div>}
